### ISSUE TITLE
Release note should not cover old release info

### ISSUE THREAD

**Issue by innobead** [SUSE/caasp-release-notes#16]
For 4.0.2 release note, it should just cover what's new/enhance/bugfix in 4.0.2 (specific version) instead of all stuff introduced from 4.x. 

https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4.0/#_changes_in_4_0_2

```
7 What Is New
7.1 Base Operating System Is Now SLES 15 SP1
7.2 Software Now Shipped As Packages Instead Of Disk Image
7.3 More Containerized Components
7.4 New Deployment Methods
7.5 Updates Using Kured
7.6 Automatic Installation Of Packages For Storage Backends Discontinued
7.7 Changes to the Kubernetes Stack
7.8 Centralized Logging
7.9 Obsolete Components
```

Ref: the example of openshift release note: https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html

cc @jenting @c3y1huang @cclhsu @jordimassaguerpla @cclhsu

**Comment by r0ckarong** [comment]
I agree. This should be incremental and limited to the scope of the related release.

**Comment by jordimassaguerpla** [comment]
I would propose we change the "What is New" to "What is New in CaaSP 4.0"

**Comment by r0ckarong** [comment]
I would propose we implement these changes from 4.0.3 onward otherwise we have to rebuild the release notes package and it's not critical.

**Comment by jordimassaguerpla** [comment]
> I would propose we implement these changes from 4.0.3 onward otherwise we have to rebuild the release notes package and it's not critical.

sure. There is no need to rerelease 4.0.2

**Comment by jordimassaguerpla** [comment]
I am sending a PR about RN for 4.0.3 in short, so I Can put this change.
