### ISSUE TITLE
Wrong pointers to SUSE docs

### ISSUE THREAD

**Issue by zoopster** [SUSE/caasp-release-notes#58]
This
https://www.suse.com/releasenotes/x86_64/SUSE-CAASP/4/#_metrics_server
has a link pointing to this
https://documentation.suse.com/suse-caasp/4.2/caasp-admin/#monitoring_stack
which throws a 404. 
Instead the link appears to be
https://documentation.suse.com/suse-caasp/4.2/single-html/caasp-admin/#_monitoring_certificates

**Comment by zoopster** [comment]
Same 404 issue in the 2.4 Cert Status Checker section, the 2.5 VSphere Storage section, and 2.6 Required Actions section.
2.8 is the only one that points to /single-html/

**Comment by innobead** [comment]
cc @nkoranova @r0ckarong

**Comment by nkoranova** [comment]
Thanks for the bugreport. Fixed this with https://github.com/SUSE/caasp-release-notes/commit/f650ab70d7c3af33bfbe1dd10bae0a5232019975 as well a few other smallish issues I noticed.
Will ask @jordimassaguerpla for a rebuild of the release notes.

**Comment by r0ckarong** [comment]
This was closed with https://github.com/SUSE/caasp-release-notes/commit/cca50971cdefb17d37baabf77ab0d61cb1a70832
