### ISSUE TITLE
minor 5.0.0 fixes

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/caasp-release-notes#73]
There are these things into the release notes that need to be fixed:

 [ ] `// * Various other fixes and improvements, refer to: https://github.com/SUSE/doc-caasp/releases/tag/release-5.0.0-beta`
 [ ] ` The most recent version of the Release Notes is available online at https://susedoc.github.io/r/caasp-5-rn.`
 [ ] And then can we make https://susedoc.github.io/caasp-release-notes/beta/html/release-notes/ point to 4.5.0 (master) ?

**Comment by jordimassaguerpla** [comment]
@r0ckarong Could you fix this?

**Comment by r0ckarong** [comment]
```
The most recent version of the Release Notes is available online at https://susedoc.github.io/r/caasp-5-rn.
```

@jordimassaguerpla Which file/URL does this sentence come from? I can't find this.

**Comment by r0ckarong** [comment]
I fixed the redirects and removed the beta branch for the v5 RN from the preview site since this is not used right now, should resolve itself once the site is rebuild during the night I guess. If not fixed in the morning I will ping Stefan.
