### ISSUE TITLE
mention helm2 and helm3

### ISSUE THREAD

**Issue by jordimassaguerpla** [SUSE/caasp-release-notes#74]
Feedback from Klaus
Section 4 (what's new in 4.5.0) should mention helm3 and the plans we have for it. Currently helm3 is only mention in section 5 (documentation changes).

release notes should mention 3 things: 1) availability of helm3 and why it's better, 2) it's not fully compatible to helm2 so we don't change the default yet which might break user's charts, 3) link to admin guide on how to adapt helm charts to helm3.

https://susedoc.github.io/caasp-release-notes/master/single-html/release-notes/

**Acceptance Criteria:**
[ ] Create PR to release notes outlining the Helm 3 availability and improvement

**Comment by jordimassaguerpla** [comment]
To be released as a maintenance update (ready at FCS) so we do not invalidate QA testing on GA.

**Comment by jordimassaguerpla** [comment]
@jodavis-suse Can you help us with this content?

**Comment by jodavis-suse** [comment]
> @jodavis-suse Can you help us with this content?

Will do.

**Comment by jodavis-suse** [comment]
PR https://github.com/SUSE/caasp-release-notes/pull/75 ready for review.

**Comment by dannysauer** [comment]
PR was merged; closing.
